### ISSUE TITLE
Camera control from CZML and/or KML

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_cesium#1]
https://groups.google.com/forum/#!topic/cesium-dev/fJfxJQU3PPg

**Comment by axisofentropy** [comment]
I looked into extending CZML but it made my head hurt so I'll try again Friday.  CZML is very extensible.  There's an Array `Cesium.CzmlDataSource.updaters` of parsing functions and we can add to the Array either within our app or within the Cesium core (the eventual goal).

Relevant email thread: https://groups.google.com/forum/#!topic/cesium-dev/_04FKS6zups

Looking at the functions already in that Array, most of them soon call https://cesiumjs.org/Cesium/Build/Documentation/CzmlDataSource.html#.processPacketData (this is the confusing bit.)

Our new parser will eventually call this: https://cesiumjs.org/Cesium/Build/Documentation/Camera.html#flyTo

**Comment by axisofentropy** [comment]
The most recent email from the cesium developers is very helpful laying out a design:

> I'm not sure if this is something we would want to add to the CZML specification, so starting with KML or your own custom data source would probably be your best bet.

> For KML, In order to have the exact same behavior seen in Google Earth you will need to make changes to both the Camera.flyTo functionality and the KmlDataSource.  Currently, camera flights operate independently from the clock on the timeline.  In order to make the camera fly back and forth as you scrub the timeline, you would need to make the camera update happen based on the application clock instead of the system clock.  Then in KmlDataSource.load you would need to write code to create camera flights based on whatever data is in the KML document.  Finally, you would need to make some changes to KmlDataSource.update to move the camera based on the time.  I think that would be it.  This isn't part of the code I'm super familiar with, so I'd have to ask other members of the team to see if there's something I'm forgetting.

> If you would like to take a stab at implementing this, let me know and I'll create an issue on our GitHub with some more details.  And if you get it working, we would really appreciate the contribution back!

> Best,

> Hannah

https://groups.google.com/d/msg/cesium-dev/fJfxJQU3PPg/mbxHmTMIBgAJ

**Comment by axisofentropy** [comment]
Flyto's are "shakey". We'll improve them.

**Comment by Davejenk1ns** [comment]
Simply going from Point A to Point B in a given scene is _barely_ sufficient.  Having multiple waypoints in a given scene would be very helpful, but not absolutely required.

**Comment by wzin** [comment]
**Requirements:**
- support for parsing KML to support:
 - kml lookat
 - kml camera
- conversion between CZML and KML metrics

**Comment by wzin** [comment]
deviation: 8 -> 21

**Comment by kiselev-dv** [comment]
## Test scenario:

1. Deploy cesium on a system (already done on qatn)
2. Load scene with kml with data for smartrack. We already have some sample scenes on qatn cms. If not ask @b-berry to add them. Check that all viewports have data (chart bars).
3. Load another scene, previous data should diappear.
4. Load scene with fly-to scenario, on qatn there are many of them in DE sction of ROS CMS or better ask Brian if he can setup a scene with fly-to which will be used for Smartrac presentation.
  - Camera should fly accordingly the data inside scene
  - Check that all viewport flyes and camera sync isn't briken
  - After camera flew, fly around with spacenav, the spacenav fly should continues form the point where camera flew duiring the presentation.
  - Fly to the place on globe opposite the camera destination and run fly-to scene again, to check that camera moves around the glob, not through.

**Comment by FuriousJulius** [comment]
Tested.
