### ISSUE TITLE
Research Offline Elevation Data

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_cesium#10]
Elevation Data is served separately from tilesets in #5 . We'll need a solution that works for either zero or very slow and unreliable Internet connections.

**Comment by axisofentropy** [comment]
This would be nice for the January project, but is not required.  Of all January's "stretch goals", this is the most valuable.

**Comment by bengoldstein** [comment]
@kiselev-dv, please update this issue. - Thanks, Ben

**Comment by kiselev-dv** [comment]
Wrote to http://viewfinderpanoramas.org/ owner

**Comment by kiselev-dv** [comment]
## Testing

1. Turn on terrain. set terrain ros parameter to http://192.168.1.217:8000/tilesets/world
2. relaunch cesium with that parameter 
3. observe the earth, check that there is a 3d relief
4. check for artifacts, like extrremly high spikes, etc

**Comment by minshallj** [comment]
![image](https://cloud.githubusercontent.com/assets/2132951/21411143/ecffb9d2-c79a-11e6-83b2-78ceadc5d43d.png)


The middle three have the terrain turned on

**Comment by kiselev-dv** [comment]
I think we can close Research ticket, and continue with #22 and #21 #19

**Comment by kiselev-dv** [comment]
Here is my conversation with Jonathan from viewfindef panoramas which elevation data sources we are using now:


On Mon, 19 Dec 2016 18:51:11 -0400, Дмитрий Киселев wrote:

> Good day Jonathan.
> 
> Can I ask your permission to use your dem data collection inside
> Cesium.js inside Liquid Galaxy.
> 
> Some details:
> I'm working on Liquid Galaxy, it's multiviewport system for 3d
> geospatial presentations with Google Earth, Cesium
> etc. https://github.com/EndPointCorp/lg_ros_nodes [1]
> 
> One of the application we are using in Liquid Galaxy is Cesium.js it's
> Google-Earth like js application
> https://github.com/AnalyticalGraphicsInc/cesium [2]
> 
> Cesium has optional support of DEM via Agi servers or via local DEM
> server. I'm working on local DEM server, and use your data as source
> of DEM.
> 
> Which form of attribution is the best?
> Now I use "Elevation data by viewfinderpanoramas.org [3]"

This is the answer

> Good day Dmitry,
> 
> Thank you for your e-mail and interest in the data on my site.
> 
> You are welcome to use these data. A link to my site is appreciated.
> 
> best regards
> Jonathan
