### ISSUE TITLE
Package and Automate Deployment to Roscoe systems

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_cesium#11]
This repository's ROS node should be ready for packaging into `.deb` and deployment via `chef` to all Roscoe systems.

We'll also want a new chef "template" that deploys this node instead of Earth on a few specific sites.

**Comment by kannan4k** [comment]
I've configured a jenkins job long back to create debs and publish to aptly. 

http://lg-ci-01.endpoint.com:8080/job/lg_cesium_deb_builds/8/console

Looks like there are some issues, will be looking into it.

**Comment by kiselev-dv** [comment]
Hi @kannan4k, I've also add mapproxy to cache imagery. I've done recipe for mapproxy deploymant it's in lg_chef repo, but I'm not sure that I've covered all points what's needed for curent configuration.

It's in ~/src/mapproxy/mapproxy.yaml also we need to open a port for mapproxy, I use 8282 and 4242 (8282 for mapproxy itself and 4242 for nginx proxy over that), and I've add a small nginx cache for mapproxy requests. Can you also look into deployment of that stuff?

**Comment by kannan4k** [comment]
@axisofentropy Found some package name issues in the aptly script. I've fixed them. 

Also configured the `catkin_generate_changelogs` and `catkin_prepare_release`  and releases the newer set of packages.
Here is portapt link -> https://portapt.galaxy.endpoint.com:5832/lg-cesium-indigo-0.0.5/

Next step is to configure this in a lg_version yaml file and create a new iso. So the lg_cesium package should be landed in a roscoe version right? rc version of this? https://github.com/EndPointCorp/lg_version/blob/master/releases/1.1.2-roscoe.yml

**Comment by kannan4k** [comment]
@kiselev-dv I am not sure what should be needed for the current configuration. Could we talk about this tomorrow?

**Comment by wzin** [comment]
@kannan4k we're working on rascal so newer version of rascal. https://github.com/EndPointCorp/lg_version/blob/master/releases/2.1.1-liquidgalaxy-rc5.yml is the latest right now. WE're not going to make any new roscoe releases (v 1.x+) unless it's security thing.

**Comment by kiselev-dv** [comment]
@kannan4k we put it on hold for now. So just forget about it for now.

**Comment by wzin** [comment]
deviation 5 -> 21

**Comment by kannan4k** [comment]
ISO has been built -> http://lg-ci-01.endpoint.com:8080/job/ISO_build_test_and_publish/401/console

https://github.com/EndPointCorp/lg_version/blob/master/releases/2.1.1-liquidgalaxy-rc7.yml#L13

Next step is 
- Deploy ISO somewhere 
- Make changes in the node def to support the lg_cesium 

@axisofentropy Can we deploy ``2.1.1-liquidgalaxy-rc7.iso`  on the qatn, where all the testing is going on? Please suggest!

**Comment by kannan4k** [comment]
We have deployed the iso on devtn and tested the changes. 

:+1: Thanks @minshallj and @FuriousJulius
