### ISSUE TITLE
Handle and/or Hide Cesium Exceptions

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_cesium#13]
Some Cesium Exceptions create a modal crash window that covers the entire browser.  On an LG, this requires a relaunch to resume.  If some of these exceptions could be handled without disrupting the experience and/or restarting Cesium, that'd be valuable.

**Comment by bengoldstein** [comment]
Crashes so far are not a big issue, but it would be good to protect ourselves from this since Adam has observed this.

Adam thinks that this may be an easy configuration option in Cesium. If so, it is worth doing for now. Alternatively, if this required core changes to Cesium we should delay this until after we get our MVP completed.

**Comment by wzin** [comment]
Use rosparam of:

`/lg_debug`:`true|false`

NOTE: this is a global param

**Comment by wzin** [comment]
deviation 5 -> 13

**Comment by kiselev-dv** [comment]
## Testing scenario

1. Turn off debug (lg_debug ros parameter)
2. Check that debug is turned off (check for FPS counter in upper left corner, it should be hidden)
3. Generate error, to do that, 
    - forward browser debug `lg-ssh --browser-forward "9292:lg_browser_cesium_30.00.00.0"`
    - go to localhost:9292
    - enter Cesium viewer console
    - trigger rendering error, by entering `viewer.scene.renderError.raiseEvent(viewer.scene, {message: 'Wassup!'})`

Check that 
- there is no overlays with messages visible to user
- viewport should restart itself in 0ne second
- check that there is a message on /cesium/crash with details

**Comment by minshallj** [comment]
that worked great, we merged master in and made one small commit on top, moving the advertise to the spot right after creating the topic allows us to listen in on the topic without getting an error. It's a best practice to advertise all topics after creating them, we once had an error with soft_relaunches that was only solved by advertising the topic even when listening in on it iirc

**Comment by minshallj** [comment]
Debug doesn't turn on when lg_debug is set to True
