### ISSUE TITLE
Fix offline elevation errors

### ISSUE THREAD

**Issue by kiselev-dv** [EndPointCorp/lg_cesium#19]
Generated set has some errors.

1. Some data missed
2. There are "walls" on tiles borders in oceans
3. There are spikes some here and there

**Requirements**:
* [ ] we need a tool to easily debug elevation (check the QGIS abilities)
* [ ] check layers.json format, check `ocean mask`, how it works
* [ ] generate additional tiles for missed areas

Missed areas:
- Siberia
- South America
- North Canada
- Kamchatka

**Comment by bengoldstein** [comment]
The missed areas cited are probably not needed for the MVP.

How bad are the "walls" and spikes?

**Comment by kiselev-dv** [comment]
Spikes aren't so bad, but walls looks pretty ugly, you can ask Josh and he will show it to you with HG

**Comment by axisofentropy** [comment]
@kiselev-dv how is this all implemented?  What's the stack?

**Comment by kiselev-dv** [comment]
@axisofentropy https://github.com/EndPointCorp/lg_cesium/blob/master/dem/DEM.md

**Comment by wzin** [comment]
Created 21 and 22
