### ISSUE TITLE
Geographic Annotation File Loader

### ISSUE THREAD

**Issue by axisofentropy** [EndPointCorp/lg_cesium#2]
Cesium can import geographic annotations from several file formats, including KML and its own CZML.  Our wrapper needs a way to import these upon demand from a URL, and then possibly execute additional API commands if needed to "kick off" the Scene.

We'd like this to support both KML and CZML, but if this isn't easy, just support CZML and we can convert.

**Comment by kiselev-dv** [comment]
cesium now listens on director/scene topic for `earth` activity, and loads kml/czml assets

**Comment by kiselev-dv** [comment]
## TODO:

* [ ] listens for cesium activity

**Comment by bengoldstein** [comment]
@kiselev-dv, is this ready for testing? If so, please move it to that column.

**Comment by wzin** [comment]
**Requirements**:
- small javascript snippet that listens for scenes and parses assets
- KML and CZML should be parsed and loaded
- assets should be loaded as assets to cesium

**Comment by joshuanorman** [comment]
Am I supposed to test this? Where can I find it? What am I looking for?

**Comment by kiselev-dv** [comment]
See test scenario for https://github.com/EndPointCorp/lg_cesium/issues/1
cc: @joshuanorman

**Comment by FuriousJulius** [comment]
@kiselev-dv we followed the testing scenario for #1 , flyto's and space nav work as expected.  Can we close this ticket as well?

**Comment by kiselev-dv** [comment]
Think so
